services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: uoc-poc-punters
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  